### ISSUE TITLE
Mobile View Layout issue

### ISSUE THREAD

**Issue by gthaka** [jkariukidev/personal-website#26]
When one opens the web page on mobile, the sidebar is not optimized. See screenshot below.

![Screenshot_20230217-222055_Chrome.jpg](https://user-images.githubusercontent.com/6692971/219767655-628f00d5-466c-4cb1-8b8c-5d12bbe64d5d.jpg)

**Comment by jkariukidev** [comment]
thanks @gthaka please transfer this issue to the actual project.

**Comment by jkariukidev** [comment]
Issue resolved in the actual repo. Please refer it [here](https://github.com/jkariukidev/personalwebsite/commit/d374936c1f5d284c3476d283e7f0720b3660fb7f)
